### ISSUE TITLE
Figure out if Marketplace update can be turned off

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#393]
Looks like marketplace release is adhoc with openshift release and even we do latest z stream release and try that after an new marketplace release then it start pulling images from the internet and which is around ~500Mb data. We need to figure out if there is a way to turn off that auto update on marketplace operator side so it will not update automatic and use whatever we have at time of bundle creation.

**Comment by praveenkumar** [comment]
After digging in the maketplace pod side looks like it using `imagePullPolicy: Always` which force to go to network and pull the metadata or images.
```
      imagePullPolicy: Always
      volumeMounts:
        - name: certified-operators-token-64gg9
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'registry.redhat.io/redhat/certified-operator-index:v4.7'
```
